---
# [Required]. A connection profile contains information about a set of network
# components. It is typically used to configure gateway, allowing applications
# interact with a network channel without worrying about the underlying
# topology. A connection profile is normally created by an administrator who
# understands this topology.
#
name: "Buyer Seller Network"
# [Optional]. Analogous to HTTP, properties with an "x-" prefix are deemed
# "application-specific", and ignored by the gateway. For example, property
# "x-type" with value "hlfv1" was originally used to identify a connection
# profile for Fabric 1.x rather than 0.x.
#
x-type: "hlfv1"
#
# [Required]. A short description of the connection profile
#
description: "A connection profile for this simple seller and buyer network"
#
# [Required]. Connection profile schema version. Used by the gateway to
# interpret these data.
#
version: "1.0"
#
# [Optional]. A logical description of each network channel; its peer and
# orderer names and their roles within the channel. The physical details of
# these components (e.g. peer IP addresses) will be specified later in the
# profile; we focus first on the logical, and then the physical.
#
channels:
  #
  # [Optional]. tradenet is the only channel in this connection profile
  #
  channel-seller:
    #
    # [Optional]. Channel orderers for tradeNet. Details of how to connect to
    # them is specified later, under the physical "orderers:" section
    #
    orderers:
      #
      # [Required]. Orderer logical name
      #
        - orderer.admincom
      #
      # [Optional]. Peers and their roles
      #
    peers:
    #
    # [Required]. Peer logical name
    #
      peer0.seller.admincom:
        #
        # [Optional]. Is this an endorsing peer? (It must have chaincode
        # installed.) Default: true
        #
        endorsingPeer: true
        #
        # [Optional]. Is this peer used for query? (It must have chaincode
        # installed.) Default: true
        #
        chaincodeQuery: true
        #
        # [Optional]. Is this peer used for non-chaincode queries? All peers
        # support these types of queries, which include queryBlock(),
        # queryTransaction(), etc. Default: true
        #
        ledgerQuery: true
        #
        # [Optional]. Is this peer used as an event hub? All peers can produce
        # events. Default: true
        #
        eventSource: true
      #
      peer0.bank.admincom:
        endorsingPeer: true
        chaincodeQuyer: true
        ledgerQuery: true
        eventSource: true

  channel-buyer:
    orderers:
        - orderer.admincom
    peers:
      peer0.buyer.admincom:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
        
      peer0.bank.admincom:
        endorsingPeer: true
        chaincodeQuyer: true
        ledgerQuery: true
        eventSource: true
#
# [Required]. List of organizations for all channels. At least one organization
# is required.
#
organizations:
  #
  # [Required]. Organizational information for Bank
  #
  Bank:
    #
    # [Required]. The MSPID used to identify Bank
    #
    mspid: BankMSP
    #
    # [Required]. The Bank peers
    #
    peers:
      - peer0.bank.admincom
    #
    # [Optional]. Fabric-CA Certificate Authorities.
    #
    certificateAuthorities:
      - ca.bank.admincom
    signedCert: 
      path: ../crypto-config/peerOrganizations/bank.admincom/users/Admin@bank.admincom/msp/signcerts/Admin@bank.admincom-cert.pem

  Seller:
    mspid: SellerMSP
    peers:
      - peer0.seller.admincom
    certificateAuthorities:
      - ca.seller.admincom
    signedCert: 
      path: ../crypto-config/peerOrganizations/seller.admincom/users/Admin@seller.admincom/msp/signcerts/Admin@seller.admincom-cert.pem

  Buyer:
    mspid: BuyerMSP
    peers:
      - peer0.buyer.admincom
    certificateAuthorities:
      - ca.buyer.admincom
    signedCert: 
      path: ../crypto-config/peerOrganizations/buyer.admincom/users/Admin@buyer.admincom/msp/signcerts/Admin@buyer.admincom-cert.pem

orderers:
  #
  # [Required]. Name of Seller orderer
  #
  orderer.admincom:
    #
    # [Required]. This orderer's IP address
    #
    url: grpcs://localhost:7050
    #
    # [Optional]. gRPC connection properties used for communication
    #
    grpcOptions:
      ssl-target-name-override: orderer.admincom
      grpc-max-send-message-length: 150000
    tlsCACerts: 
      path: ../crypto-config/ordererOrganizations/admincom/msp/tlscacerts/tlsca.admincom-cert.pem
#
# [Required]. Peer physical information, by peer name. At least one peer is
# required.
#
peers:
  #
  # [Required]. Seller peer physical properties
  #
  peer0.bank.admincom:
    #
    # [Required]. Peer's IP address
    #
    url: grpcs://localhost:7051
    eventUrl: grpcs://localhost:7053
    #
    # [Optional]. gRPC connection properties used for communication
    #
    grpcOptions:
      ssl-target-name-override: peer0.bank.admincom
      request-timeout: 120001
    tlsCACerts: 
      path: ../crypto-config/peerOrganizations/bank.admincom/peers/peer0.bank.admincom/msp/tlscacerts/tlsca.bank.admincom-cert.pem
  #
  # [Required]. Seller peer physical properties
  #
  peer0.seller.admincom:
    url: grpcs://localhost:8051
    eventUrl: grpcs://localhost:8053
    grpcOptions:
      ssl-target-name-override: peer0.seller.admincom
      request-timeout: 120001
    tlsCACerts: 
      path: ../crypto-config/peerOrganizations/seller.admincom/peers/peer0.seller.admincom/msp/tlscacerts/tlsca.seller.admincom-cert.pem
  #
  # [Required]. Buyer peer physical properties
  #
  peer0.buyer.admincom:
    url: grpcs://localhost:9051
    eventUrl: grpcs://localhost:9053
    grpcOptions:
      ssl-target-name-override: peer0.buyer.admincom
      request-timeout: 120001
    tlsCACerts: 
      path: ../crypto-config/peerOrganizations/buyer.admincom/peers/peer0.buyer.admincom/msp/tlscacerts/tlsca.buyer.admincom-cert.pem
#
# [Optional]. Fabric-CA Certificate Authority physical information, by name.
# This information can be used to (e.g.) enroll new users. Communication is via
# REST, hence options relate to HTTP rather than gRPC.
#
# certificateAuthorities:
#   #
#   # [Required]. Seller's CA
#   #
#   ca.seller.admincom:
#   #
#   # [Required]. CA IP address
#   #
#   url: http://localhost:7053
#   #
#   # [Optioanl]. HTTP connection properties used for communication
#   #
#   httpOptions:
#     verify: false
#   tlsCACerts:
#     path: crypto-config/peerOrganizations/seller.admincom/ca.seller.admincom-cert.pem
#   #
#   # [Optional]. Fabric-CA supports Certificate Signing Requests (CSRs). A
#   # registrar is needed to enroll new users.
#   #
#   registrar:
#     - enrollId: admin
#     enrollSecret: adminpw
#   #
#   # [Optional]. The name of the CA.
#   #
#   caName: ca-seller
# certificateAuthorities:
#   #
#   # [Required]. Buyer's CA
#   #
#   ca.buyer.admincom:
#   #
#   # [Required]. CA IP address
#   #
#   url: http://localhost:7053
#   #
#   # [Optioanl]. HTTP connection properties used for communication
#   #
#   httpOptions:
#     verify: false
#   tlsCACerts:
#     path: crypto-config/peerOrganizations/buyer.admincom/ca.buyer.admincom-cert.pem
#   #
#   # [Optional]. Fabric-CA supports Certificate Signing Requests (CSRs). A
#   # registrar is needed to enroll new users.
#   #
#   registrar:
#     - enrollId: admin
#     enrollSecret: adminpw
#   #
#   # [Optional]. The name of the CA.
#   #
#   caName: ca-seller