version: '2'

volumes:
  orderer.yunxi.com:
  seller.seller.yunxi.com:
  buyer.buyer.yunxi.com:

networks:
  seller-buyer-network:

services:

  orderer.yunxi.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.yunxi.com
    container_name: orderer.yunxi.com
    networks:
      - seller-buyer-network

  peer0.seller.yunxi.com:
    container_name: peer0.seller.yunxi.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.seller.yunxi.com
    networks:
      - seller-buyer-network

  peer0.buyer.yunxi.com:
    container_name: peer0.buyer.yunxi.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.buyer.yunxi.com
    networks:
      - seller-buyer-network

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.seller.yunxi.com:7051
      - CORE_PEER_LOCALMSPID=SellerMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/seller.yunxi.com/peers/peer0.seller.yunxi.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/seller.yunxi.com/peers/peer0.seller.yunxi.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/seller.yunxi.com/peers/peer0.seller.yunxi.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/seller.yunxi.com/users/Admin@seller.yunxi.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.yunxi.com
      - peer0.seller.yunxi.com
      - peer0.buyer.yunxi.com
    networks:
      - seller-buyer-network