NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.seller.yunxi.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.seller.yunxi.com-cert.pem
    OrganizationalUnitIdentifier: peer
